### ISSUE TITLE
ModuleNotFoundError: No module named 'buildamol.optimizers.translatron'

### ISSUE THREAD

**Issue by yuqiusanofi** [ibmm-unibe-ch/glycosylator#1]
ModuleNotFoundError: No module named 'buildamol.optimizers.translatron'
Happens when "import glycosylator as gl"

**Comment by NoahHenrikKleinschmidt** [comment]
Heyhow, 
Sorry to hear you're having an issue. Yes there were some compatibility issues with BuildAMol and different Python distributions. The newest release `v.1.2.0` was supposed to fix these by refactoring and renaming some files. May I ask what BuildAMol version you are running?
