### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by cesar-lopez-bau** [ibmm-unibe-ch/glycosylator#5]
Hi;

trying to follow the tutorial, while trying to glycosylate the protein I get the following:

  File "/scratch/GLYCOSYLATOR/GLYCOSYLATE-PROTEIN.sh", line 10, in <module>
    glycoprotein = gl.glycosylate(protein, glycan, sequon="N-linked")
  File "/home/clopez/anaconda3/lib/python3.10/site-packages/glycosylator/core/scaffold.py", line 169, in glycosylate
    return scaffold.attach(
  File "/home/clopez/anaconda3/lib/python3.10/site-packages/glycosylator/core/protein_scaffold.py", line 275, in attach
    scaffold = Scaffold.attach(
  File "/home/clopez/anaconda3/lib/python3.10/site-packages/glycosylator/core/scaffold.py", line 1248, in attach
    scaffold, _mol = s.apply(
  File "/home/clopez/anaconda3/lib/python3.10/site-packages/buildamol/structural/stitch.py", line 125, in apply
    self._align_anchors()
  File "/home/clopez/anaconda3/lib/python3.10/site-packages/buildamol/structural/stitch.py", line 139, in _align_anchors
    ref_target_atom = next(i for i in neighs if i in self._removals[0])
StopIteration

Not sure what it is wrong

thanks

**Comment by NoahHenrikKleinschmidt** [comment]
Hi there, 

Sorry to hear that something isn't working. Can you be more specific about what you were trying to do 🙈? 
I assume you were trying to run the example code from the main README file, correct? 
If so, there are several possible reasons why it did not work—these code snippets are more "examples" than actual tutorials (depending on the protein and glycan used, other steps are necessary). We have a "proper" [tutorial in the documentation](https://glycosylator.readthedocs.io/en/latest/examples/glycosylate_protein.html), which should definitely work. 

If you like, we can look further into why your code was failing :-) Then I would need to see the code and, ideally, also the protein/glycan inputs at some point. 

<details>
  <summary>Spontaneous thoughts on the "StopIteration"</summary>

  The most common cause for this error is missing bond information in either the protein or glycan. When trying to connect the two molecules, Glycosylator will try to find atoms to remove based on their connectivity, but if no bonds are defined, then no connectivity is known and the program crashes. 

Possible fixes for this are either `mol.infer_bonds()` or `mol.apply_standard_bonds()`.

Alternatively, it is possible that Hydrogens are missing from either the protein or glycan, in which case `mol.add_hydrogens()` would be the way to go (but this also requires bond information to be present first).

</details>

**Comment by cesar-lopez-bau** [comment]
Hi;

I fix the issue, it seems the file I was using were corrupted somehow. Thanks, one question aside, is there a way to glycosylate the proteins with more than a type of glycan and in specific residues?

**Comment by NoahHenrikKleinschmidt** [comment]
Great to hear that!

### Glycosylate at specific Residues 
Yes. To glycosylate at specific residues you can simply call `protein.glycosylate` while providing the `residues` argument with a list of `Residue` objects or other identifiers (residue serial numbers for instance)  Like so:

```python
# add the glycan specifically to residues number 102, 123, and 256
glycoprotein = protein.glycosylate(glycan1, residues=[102, 123, 256])
```

### Adding multiple Glycans
There is no way to directly provide multiple glycans to `protein.glycosylate` but you can simply call the method multiple times, once for each glycan you want to work with, and provide again a list of target residues. Like so:

```python
# adding inplace=True to make sure we edit the same object
protein.glycosylate(glycan1, residues=[150, 173, 221], inplace=True)
protein.glycosylate(glycan2, residues=[49, 155, 312], inplace=True)
...
```
